export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const SET_ADD_MODAL_VISIBILITY = 'SET_ADD_MODAL_VISIBILITY';
export const visibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
};

//Auth actions
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

//Device token registration
export const SET_DEVICE_TOKEN = 'SET_DEVICE_TOKEN';
export const DEVICE_TOKEN_REGISTRATION = 'DEVICE_TOKEN_REGISTRATION';
export const DEVICE_TOKEN_UNREGISTRATION = 'DEVICE_TOKEN_UNREGISTRATION';
export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION';
export const ADD_NEW_HOUSE = 'ADD_NEW_HOUSE';
export const GET_ALL_HOUSEs = 'GET_ALL_HOUSEs';
